const DB_NAME='travel-journal-db', STORE='trips';
const countries={馬來西亞:'🇲🇾',泰國:'🇹🇭',台灣:'🇹🇼',日本:'🇯🇵',中國:'🇨🇳',韓國:'🇰🇷'};
const seed=[{id:'seed-1',title:'東京櫻花之旅',country:'日本',origin:'台北 TPE',destination:'東京 NRT',startAt:'2026-10-04T09:15',endAt:'2026-10-09T18:30',airline:'中華航空',flight:'CI100',companions:'',budget:'',custom:{},itinerary:[]}];
const app=document.querySelector('#app'), dialog=document.querySelector('#tripDialog'), form=document.querySelector('#tripForm'), fields=document.querySelector('#customFields');
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getTrips(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putTrip(t){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(t);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
async function ensureSeed(){if(!(await getTrips()).length) for(const t of seed) await putTrip(t)}
function duration(t){if(!t.startAt||!t.endAt)return '日期待定';return `${Math.max(1,Math.round((new Date(t.endAt)-new Date(t.startAt))/86400000))} 天 ${Math.max(0,Math.round((new Date(t.endAt)-new Date(t.startAt))/86400000)-1)} 夜`}
function dateText(t){return t.startAt?new Intl.DateTimeFormat('zh-TW',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(t.startAt)):'日期待定'}
function card(t){const upcoming=!t.startAt||new Date(t.endAt||t.startAt)>=new Date();return `<article class="trip-card"><span class="status">${upcoming?'即將出發':'已完成'}</span><h3>${escapeHtml(t.title)}</h3><p class="route">${escapeHtml(t.origin||'出發地')} → ${escapeHtml(t.destination||t.country)}</p><p class="meta">${dateText(t)}<br>${duration(t)}${t.flight?` · ${escapeHtml(t.flight)}`:''}</p><button class="text-action" data-trip="${t.id}">查看旅程 →</button></article>`}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[s]))}
async function home(){const trips=await getTrips();const upcoming=trips.filter(t=>!t.startAt||new Date(t.endAt||t.startAt)>=new Date());const past=trips.filter(t=>t.startAt&&new Date(t.endAt||t.startAt)<new Date());app.innerHTML=`<section class="hero"><div><p class="eyebrow">PERSONAL TRAVEL ARCHIVE</p><h1>把走過的世界<br>好好收藏起來。</h1><p>行程、行李、預算與旅途記憶，都在屬於你的旅跡裡。</p></div><button id="openDialog">＋ 建立我的旅程</button></section><section class="section"><div class="section-title"><div><p class="eyebrow">MY FOOTPRINTS</p><h2>我去過的國家</h2></div><p>${Object.keys(countries).length} 個國家</p></div><div class="country-grid">${Object.entries(countries).map(([n,f])=>`<button class="country" data-country="${n}"><span class="flag">${f}</span><b>${n}</b><small><br>查看旅遊紀錄</small></button>`).join('')}</div></section><section class="section"><div class="section-title"><div><p class="eyebrow">UP NEXT</p><h2>目前／未來行程</h2></div></div><div class="trip-grid">${upcoming.map(card).join('')||'<div class="empty">還沒有安排中的旅行。現在就開始規劃吧！</div>'}</div></section><section class="section"><div class="section-title"><div><p class="eyebrow">MEMORIES</p><h2>過去旅行</h2></div></div><div class="trip-grid">${past.map(card).join('')||'<div class="empty">完成一趟旅行後，回憶會在這裡累積。</div>'}</div></section><section id="knowledge" class="section"><div class="section-title"><div><p class="eyebrow">TRAVEL BASICS</p><h2>旅行知識庫</h2></div></div><div class="knowledge"><article><h3>簽證與入境</h3><p>依護照別、目的地與停留目的整理免簽、電子簽、簽證與台胞證規則。</p><a href="#" onclick="alert('簽證規定常有變動，正式上線時應串接官方資訊並標示最後確認日期。');return false">查看提醒 →</a></article><article><h3>旅行必備清單</h3><p>證件、支付、網路、藥品、衣物與 3C；可依季節與行程建立個人範本。</p><a href="#" onclick="alert('建立旅程後，可為每一趟新增專屬行李清單與自訂欄位。');return false">查看清單 →</a></article><article><h3>出發前倒數</h3><p>護照效期、保險、線上報到、換匯與訂位取消期限，避免臨行前遺漏。</p><a href="#" onclick="alert('下一版建議加入提醒通知與預訂截止日。');return false">查看待辦 →</a></article></div></section>`;bindHome()}
function bindHome(){document.querySelector('#openDialog')?.addEventListener('click',()=>dialog.showModal());document.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>countryPage(b.dataset.country));document.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>tripPage(b.dataset.trip))}
async function countryPage(name){const trips=(await getTrips()).filter(t=>t.country===name);app.innerHTML=`<button class="back" id="back">← 回到首頁</button><section class="section"><div class="detail-head"><div><p class="eyebrow">DESTINATION GUIDE</p><h1>${countries[name]||'🌍'} ${name}</h1></div><button id="newCountryTrip">＋ 前往這裡</button></div><div class="notice-grid"><article class="notice"><b>入出境與簽證</b><p>請確認護照效期、簽證或入境許可與停留天數；出發前務必以官方單位公告為準。</p></article><article class="notice"><b>退稅與消費</b><p>儲存收據並確認最低消費、退稅櫃檯位置與商品攜帶規範。</p></article><article class="notice"><b>安全與在地禮儀</b><p>建立緊急聯絡資訊、離線地圖與當地支付／網路備案。</p></article></div></section><section class="section"><p class="eyebrow">MY HISTORY</p><h2>我的 ${name} 旅行</h2><div class="trip-grid">${trips.map(card).join('')||'<div class="empty">尚未留下這個國家的旅程記錄。</div>'}</div></section>`;document.querySelector('#back').onclick=home;document.querySelector('#newCountryTrip').onclick=()=>{form.country.value=name;dialog.showModal()};document.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>tripPage(b.dataset.trip))}
async function tripPage(id){const t=(await getTrips()).find(x=>x.id===id);if(!t)return home();app.innerHTML=`<button class="back" id="back">← 回到首頁</button><section class="section"><p class="eyebrow">TRIP RECORD</p><h1>${escapeHtml(t.title)}</h1><p class="route">${escapeHtml(t.origin||'出發地')} → ${escapeHtml(t.destination||t.country)} · ${duration(t)}</p><div class="trip-grid"><article class="trip-card"><b>航班資訊</b><p class="meta">${escapeHtml(t.airline||'尚未填寫')} ${escapeHtml(t.flight||'')}<br>${dateText(t)}</p></article><article class="trip-card"><b>旅伴與預算</b><p class="meta">旅伴：${escapeHtml(t.companions||'自己') }<br>預算：${t.budget?Number(t.budget).toLocaleString():'尚未設定'}</p></article><article class="trip-card"><b>目的地注意事項</b><p class="meta">此處可儲存此次行程專屬的簽證、退稅與安全資訊快照。</p></article></div></section><section class="section"><p class="eyebrow">ITINERARY</p><h2>每日行程</h2><div class="empty">下一步可在這裡加入日期、時間、地點、交通、地圖連結、備註，以及任何自訂欄位。</div></section>`;document.querySelector('#back').onclick=home}
document.querySelector('#addFieldBtn').onclick=()=>{const row=document.createElement('div');row.className='custom-row';row.innerHTML='<input placeholder="欄位名稱，例如：飯店"><input placeholder="內容"><button type="button" class="secondary">移除</button>';row.querySelector('button').onclick=()=>row.remove();fields.append(row)};
form.addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){form.reset();fields.innerHTML='';dialog.close();return}const fd=new FormData(form),custom={};fields.querySelectorAll('.custom-row').forEach(r=>{const [k,v]=r.querySelectorAll('input');if(k.value.trim())custom[k.value.trim()]=v.value.trim()});await putTrip({id:crypto.randomUUID(),...Object.fromEntries(fd),custom,itinerary:[]});form.reset();fields.innerHTML='';dialog.close();home()});
document.querySelector('#backupBtn').onclick=async()=>{const blob=new Blob([JSON.stringify(await getTrips(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`旅跡備份-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
ensureSeed().then(home);
